name: Deploy Next.js app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build app
        run: npm run build
      
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.3.6
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}
          ssh-username: ${{ secrets.SERVER_USERNAME }}
          local-path: .next/
          remote-path: /var/www/beedev.fr
          exclude: ".next/cache/**"
          args: "-o StrictHostKeyChecking=no"
      
      - name: Restart Nginx
        run: sudo systemctl restart nginx
