name: Deploy Next.js app

on:
  push:
    branches:
      - main  # Mettez le nom de votre branche principale ici

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          SOURCE: .next/
          TARGET: /root/Portfolio
          EXCLUDE: ".next/cache/**"
          ARGS: "-o StrictHostKeyChecking=no"
