name: Deploy Next.js app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: .

      - name: Build app
        run: npm run build

      - name: Build Docker image
        run: docker build -t my-next-app .

      - name: Save Docker image as tarball
        run: |
          docker save -o my-next-app.tar my-next-app
          ls -l

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: app-files
          path: .next/

      - name: Check SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            ls /root/Portfolio/

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          source: ./
          target: /root/Portfolio/

      - name: Check Tarball on Runner
        run: ls -l

      - name: Copy Tarball to Server
        uses: appleboy/scp-action@master
        with:
          key: ${{ secrets.SERVER_SSH_KEY }}
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          source: ./my-next-app.tar
          target: /tmp/

      - name: SSH into server and load Docker image
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          PORT: 22
          SCRIPT: |
            sudo docker load -i /tmp/my-next-app.tar

      - name: Run Docker container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop my-next-app || true
            sudo docker rm my-next-app || true
            sudo docker run -d -p 3000:3000 --name my-next-app my-next-app
