name: Deploy Next.js app

on:
  push:
    branches:
      - main  # Mettez le nom de votre branche principale ici

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Build Docker image
        run: docker build -t my-next-app .

      - name: Save Docker image as tarball
        run: docker save -o my-next-app.tar my-next-app

      - name: Copy files to server
        uses: easingthemes/scp-action@v1.0.1
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}
          ssh-username: ${{ secrets.SERVER_USERNAME }}
          source: ${{ runner.temp }}/app-files
          target: /root/Portfolio/

      - name: SSH into server and load Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo docker load -i /tmp/my-next-app.tar

      - name: Run Docker container on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            sudo docker stop my-next-app || true
            sudo docker rm my-next-app || true
            sudo docker run -d -p 3000:3000 --name my-next-app my-next-app

