name: Deploy Next.js app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build app
        run: |
          npm install
          npm run build

      - name: Build Docker image
        run: docker build -t my-next-app .

      - name: Save Docker image as tarball
        run: |
          docker save -o my-next-app.tar my-next-app
          ls -l

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: app-files
          path: .next/

      - name: SSH into server and load Docker image
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          PORT: 22
          SCRIPT: |
            sudo docker load -i my-next-app.tar
            sudo docker stop my-next-app || true
            sudo docker rm my-next-app || true
            sudo docker run -d -p 3000:3000 --name my-next-app my-next-app
