name: Deploy Next.js app

on:
  push:
    branches:
      - main  # Mettez le nom de votre branche principale ici

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/Portfolio
            rm -rf ./*
            cp -r /home/runner/work/Portfolio/Portfolio/.next/* .